spring:
  datasource:
    url: jdbc:h2:file:/data/atv
    username: sa
    password: password
    driverClassName: org.h2.Driver

logging:
  file:
    name: log/app.log
  level:
    cn.har01d: info

app:
  sites:
    - name: 本地
      url: http://localhost
      version: 3
      searchable: true
      xiaoya: false
