name: Release Native Binary

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Cache GraalVM
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/graalvm
            ~/.m2
          key: ${{ runner.os }}-graalvm-${{ matrix.arch }}-${{ hashFiles('**/pom-standalone.xml') }}

      - name: Build Native Image (${{ matrix.arch }})
        run: |
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu libstdc++-12-dev-arm64-cross
          fi

          mvn -B -Pnative \
            -Dnative.image.cache=true \
            -Dnative.image.cache.dir=$HOME/.cache/graalvm \
            -Dnative.image.cache.persistent=true \
            -Dnative-image.parallelism=4 \
            -DskipTests \
            -Dnative.buildtools.build.target=${{ matrix.arch == 'arm64' && 'linux-aarch_64' || 'linux-x86_64' }} \
            --file pom-standalone.xml \
            package

          cd target
          chmod +x atv
          mv atv atv-${{ matrix.arch }}
          tar zcvf atv-${{ matrix.arch }}.tgz atv-${{ matrix.arch }}
          ls -lh

      - name: Upload Artifact (${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: target/atv-${{ matrix.arch }}.tgz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/amd64/atv-amd64.tgz
            artifacts/arm64/atv-arm64.tgz

      - name: Send version
        env:
          API_URL: ${{ secrets.VERSION_API }}
        if: ${{ env.API_URL != '' }}
        run: |
          curl -s "${{ env.API_URL }}?type=app&version=${{ github.ref_name }}"